from fastapi import FastAPI, UploadFile
from fastapi.responses import Response
from imadj.core import adjust_image
from imadj.helpers import RotationEnum

some_file_path = "tests/out.bmp"

app = FastAPI()


@app.post(
    "/api/adjust_image/",
    # Set what the media type will be in the autogenerated OpenAPI specification.
    # fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response
    responses={200: {"content": {"image/bmp": {}}}},
    # Prevent FastAPI from adding "application/json" as an additional
    # response media type in the autogenerated OpenAPI specification.
    # https://github.com/tiangolo/fastapi/issues/3258
    response_class=Response,
)
async def create_upload_file(infile: UploadFile, rotate: RotationEnum):
    image = await infile.read()
    return Response(content=adjust_image(image, rotate), media_type="image/bmp")


@app.get("/api/health")
async def health():
    return {"status": "I'm fine, thanks for asking!"}
